language:
  - python

install:
  - curl -L https://deno.land/x/install/install.py | python - v0.2.9
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - deno --version
  - deno test.ts --allow-write --allow-run --allow-env --reload --recompile

cache:
  directories:
    - '$HOME/.deno'
