language: sh

install:
  - curl -L https://deno.land/x/install/install.sh | sh
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - deno --version
  - deno test.ts --allow-write --allow-run --allow-read --allow-env --reload --recompile

cache:
  directories:
    - '$HOME/.deno'
